const types = {
  SETSCORE: "SETSCORE",
  SUMSCORE: "SUMSCORE",

  SETPLAYERCLICK: "SETPLAYERCLICK",
  SETPLEAYERTIME: "SETPLAYERTIME",
  SETPLAYERDATE: "SETPLAYERDATE",

  SETNOTI: "SETNOTI",
  DELNOTI: "DELNOTI",
};

export default types;
